/**
 * Built-in themes, upserted into the `themes` table every time the DB opens. Edit them here:
 * unlike migrations, a redeploy is all it takes.
 *
 * A theme is a set of CSS custom properties applied on top of the defaults in styles.scss, so a
 * theme only needs the tokens it changes (the full list is at the top of styles.scss). `season` (MM-DD, inclusive, may wrap past New Year)
 * makes it take over automatically on those dates when the wall is set to Automatic.
 */
export interface ThemeDef {
  id: string;
  name: string;
  scheme: 'dark' | 'light';
  tokens: Record<string, string>;
  season: { start: string; end: string } | null;
}

export const BUILTIN_THEMES: ThemeDef[] = [
  {
    id: 'dark',
    name: 'Dark',
    scheme: 'dark',
    season: null,
    tokens: {
      '--bg': '#0f1115',
      '--surface': '#181b22',
      '--surface-2': '#232733',
      '--text': '#eef0f4',
      '--text-muted': '#9aa1ae',
      '--accent': '#6cb6ff',
      '--danger': '#ff6b6b',
      '--success': '#51cf66',
      '--warn': '#ffa94d',
    },
  },
  {
    id: 'light',
    name: 'Light',
    scheme: 'light',
    season: null,
    tokens: {
      '--bg': '#eef0f4',
      '--surface': '#ffffff',
      '--surface-2': '#e2e5ec',
      '--text': '#1b1e24',
      '--text-muted': '#5f6673',
      '--accent': '#1c7ed6',
      '--danger': '#e03131',
      '--success': '#2f9e44',
      '--warn': '#d9480f',
      '--press': 'brightness(0.9)',
      '--card-shadow': '0 0.1rem 0.4rem rgb(20 25 40 / 0.08)',
      '--emoji-filter': 'drop-shadow(0 0 0.04em rgb(20 25 40 / 0.45))',
    },
  },
  {
    id: 'halloween',
    name: 'Halloween',
    scheme: 'dark',
    season: { start: '10-01', end: '10-31' },
    tokens: {
      '--bg': '#1f102b',
      '--surface': '#321c45',
      '--surface-2': '#431863',
      '--text': '#f5ecdf',
      '--text-muted': '#b09dbf',
      '--accent': '#ff7a1a',
      '--danger': '#ff5c5c',
      '--success': '#9be15d',
      '--warn': '#ffb347',
      '--font-display': "'Creepster', var(--font-body)",
      // Cobwebs in the nav (public/themes/halloween, generated by a script; see CLAUDE.md).
      // Layers stack top to bottom: corner web, side web with a spider, then the nav color.
      '--rail-bg': [
        "url('/themes/halloween/web-corner.svg') left top / 8rem no-repeat",
        "url('/themes/halloween/web-side.svg') right top 70% / 5.5rem no-repeat",
        'var(--surface)',
      ].join(', '),
      // Webs show through faintly; labels stay readable.
      '--rail-item-bg': 'rgb(31 16 43 / 0.5)',
    },
  },
  {
    id: 'thanksgiving',
    name: 'Thanksgiving',
    scheme: 'dark',
    season: { start: '11-01', end: '11-30' },
    tokens: {
      '--bg': '#511f16',
      '--surface': '#633f21',
      '--surface-2': '#57371d',
      '--text': '#f5ecdf',
      '--text-muted': '#ba6f4c',
      '--accent': '#b6562a',
      '--danger': '#ff5c5c',
      '--success': '#9be15d',
      '--warn': '#ffb347',
      '--font-display': "'Thanksgiving', var(--font-body)",
      // Flannel plaid nav, all CSS: buffalo check over the rust, with cream pinstripes.
      '--rail-bg': [
        'repeating-linear-gradient(90deg, transparent 0 1.9rem, rgb(245 236 223 / 0.3) 1.9rem 2rem)',
        'repeating-linear-gradient(0deg, transparent 0 1.9rem, rgb(245 236 223 / 0.3) 1.9rem 2rem)',
        'repeating-linear-gradient(90deg, rgb(50 18 10 / 0.45) 0 1rem, transparent 1rem 2rem)',
        'repeating-linear-gradient(0deg, rgb(50 18 10 / 0.45) 0 1rem, transparent 1rem 2rem)',
        '#b6562a',
      ].join(', '),
      '--rail-fg': '#f5ecdf',
      '--rail-item-bg': 'rgb(81 31 22 / 0.88)',
      '--rail-active-bg': '#f5ecdf',
      '--rail-active-fg': '#511f16',
      '--rail-edge': '0.15rem 0 0.8rem rgb(0 0 0 / 0.45)',
      // The rust + sits on rust plaid, so ring it in cream.
      '--rail-add-ring': '0 0 0 0.25rem #f5ecdf',
    },
  },
  {
    id: 'christmas-night',
    name: 'Christmas Night',
    scheme: 'dark',
    season: { start: '12-01', end: '12-31' },
    // Evergreen dark: cream text, cranberry accents, gold trim. Same candy-cane nav, with
    // the stripes deepened so they don't glare against the dark page.
    tokens: {
      '--bg': '#0e231a',
      '--surface': '#153325',
      '--surface-2': '#1e4532',
      '--text': '#f6efe1',
      '--text-muted': '#a7bcad',
      '--accent': '#e0444e',
      '--danger': '#ff6b6b',
      '--success': '#69db7c',
      '--warn': '#f2c14e',
      '--font-display': "'Christmas', var(--font-body)",
      '--rail-bg': 'repeating-linear-gradient(-45deg, #a3182a 0 1.1rem, #efe6d4 1.1rem 2.2rem)',
      '--rail-fg': '#f6efe1',
      '--rail-item-bg': '#153325',
      '--rail-active-bg': '#a3182a',
      '--rail-active-fg': '#f6efe1',
      '--rail-edge': '0.15rem 0 0.8rem rgb(0 0 0 / 0.45)',
      '--rail-add-ring': '0 0 0 0.25rem #efe6d4',
      '--rail-border-width': '0.15rem',
      '--rail-item-border-color': '#185237',
      '--rail-active-border-color': '#185237',
      '--rail-item-shadow': '0 0.3rem 0.9rem rgb(0 0 0 / 0.35)',
    },
  },
  {
    id: 'winter',
    name: 'Winter',
    scheme: 'light',
    season: { start: '01-01', end: '01-31' },
    // Frost: blue-white page, deep slate text, glacier-teal accent. The nav is a winter-sky
    // gradient with falling snow (public/themes/winter, from scripts/winter-snow.mjs).
    tokens: {
      '--bg': '#e8f1f8',
      '--surface': '#ffffff',
      '--surface-2': '#dce8f2',
      '--text': '#1c2b3a',
      '--text-muted': '#5d7286',
      '--accent': '#1b7fa3',
      '--danger': '#d6336c',
      '--success': '#2b8a3e',
      '--warn': '#c2570c',
      '--press': 'brightness(0.92)',
      '--card-shadow': '0 0.1rem 0.5rem rgb(30 60 100 / 0.1)',
      '--emoji-filter': 'drop-shadow(0 0 0.04em rgb(20 40 70 / 0.5))',
      '--font-display': "'Winter', var(--font-body)",
      '--rail-bg': [
        "url('/themes/winter/snow.svg') 0 0 / 6.5rem auto repeat",
        'linear-gradient(180deg, #2f6fa6 0%, #7fb3db 100%)',
      ].join(', '),
      '--rail-fg': '#1c2b3a',
      '--rail-item-bg': 'rgb(255 255 255 / 0.88)',
      '--rail-active-bg': '#1c2b3a',
      '--rail-active-fg': '#ffffff',
      '--rail-edge': '0.15rem 0 0.8rem rgb(30 60 100 / 0.25)',
      '--rail-add-ring': '0 0 0 0.25rem #ffffff',
    },
  },
  {
    id: 'valentines',
    name: "Valentine's",
    scheme: 'dark',
    // Through the 29th so leap years are covered.
    season: { start: '02-01', end: '02-29' },
    // Deep berry page, blush text, hot-pink accent. The pink lives in the nav: a pink gradient
    // with scattered hearts (public/themes/valentines, from scripts/valentines-hearts.mjs).
    tokens: {
      '--bg': '#260d1c',
      '--surface': '#361327',
      '--surface-2': '#4a1a35',
      '--text': '#fde8ef',
      '--text-muted': '#d29ab2',
      '--accent': '#ff5c9a',
      '--danger': '#ff6b6b',
      '--success': '#7ee0a8',
      '--warn': '#ffc46b',
      '--font-display': "'Valentines', var(--font-body)",
      '--rail-bg': [
        "url('/themes/valentines/hearts.svg') 0 0 / 6.5rem auto repeat",
        'linear-gradient(180deg, #ff86b6 0%, #d93a78 100%)',
      ].join(', '),
      '--rail-fg': '#fde8ef',
      '--rail-item-bg': 'rgb(38 13 28 / 0.82)',
      '--rail-active-bg': '#fde8ef',
      '--rail-active-fg': '#b3164f',
      '--rail-edge': '0.15rem 0 0.8rem rgb(0 0 0 / 0.4)',
      '--rail-add-ring': '0 0 0 0.25rem #fde8ef',
    },
  },
  {
    id: 'stpatricks',
    name: "St. Patrick's",
    scheme: 'dark',
    season: { start: '03-01', end: '03-31' },
    // Deep emerald page, cream text, pot-of-gold accent. The nav is a green gradient with
    // shamrocks (public/themes/stpatricks, from scripts/stpatricks-shamrocks.mjs) and gold trim.
    tokens: {
      '--bg': '#0b1f14',
      '--surface': '#11301f',
      '--surface-2': '#1a432d',
      '--text': '#f3f7ec',
      '--text-muted': '#9fbfa8',
      '--accent': '#f2c14e',
      '--danger': '#ff6b6b',
      '--success': '#8ce99a',
      '--warn': '#ffa94d',
      '--font-display': "'StPatricks', var(--font-body)",
      '--rail-bg': [
        "url('/themes/stpatricks/shamrocks.svg') 0 0 / 6.5rem auto repeat",
        'linear-gradient(180deg, #23874d 0%, #0e4a29 100%)',
      ].join(', '),
      '--rail-fg': '#f3f7ec',
      '--rail-item-bg': 'rgb(11 31 20 / 0.82)',
      '--rail-active-bg': '#f2c14e',
      '--rail-active-fg': '#0b1f14',
      '--rail-edge': '0.15rem 0 0.8rem rgb(0 0 0 / 0.4)',
      '--rail-add-ring': '0 0 0 0.25rem #f3f7ec',
      '--rail-border-width': '0.12rem',
      '--rail-item-border-color': 'rgb(242 193 78 / 0.55)',
      '--rail-active-border-color': '#f2c14e',
    },
  },
  {
    id: 'rain',
    name: 'Rain',
    scheme: 'dark',
    season: { start: '04-01', end: '04-30' },
    // Stormy slate page with a raincoat-yellow accent. The nav is a storm-cloud gradient with
    // blowing rain (public/themes/rain, from scripts/rain-streaks.mjs).
    tokens: {
      '--bg': '#0f1620',
      '--surface': '#17212d',
      '--surface-2': '#22303f',
      '--text': '#e6edf5',
      '--text-muted': '#93a4b8',
      '--accent': '#ffd23f',
      '--danger': '#ff6b6b',
      '--success': '#69db7c',
      '--warn': '#ffa94d',
      '--font-display': "'Rain', var(--font-body)",
      '--rail-bg': [
        "url('/themes/rain/rain.svg') 0 0 / 6.5rem auto repeat",
        'linear-gradient(180deg, #34495f 0%, #131c27 100%)',
      ].join(', '),
      '--rail-fg': '#e6edf5',
      '--rail-item-bg': 'rgb(15 22 32 / 0.8)',
      '--rail-active-bg': '#ffd23f',
      '--rail-active-fg': '#0f1620',
      '--rail-edge': '0.15rem 0 0.8rem rgb(0 0 0 / 0.45)',
    },
  },
  {
    id: 'cinco',
    name: 'Cinco de Mayo',
    scheme: 'dark',
    season: { start: '05-01', end: '05-31' },
    // Fiesta at night: deep indigo page, warm cream text, marigold accent. The nav hangs
    // strings of papel picado (public/themes/cinco, from scripts/cinco-papel-picado.mjs).
    tokens: {
      '--bg': '#14121f',
      '--surface': '#1f1b2e',
      '--surface-2': '#2c2640',
      '--text': '#fff4e6',
      '--text-muted': '#bfb2c9',
      '--accent': '#ffb000',
      '--danger': '#ff6b6b',
      '--success': '#3ddc97',
      '--warn': '#ff7a1a',
      '--font-display': "'Cinco', var(--font-body)",
      '--rail-bg': [
        "url('/themes/cinco/papel-picado.svg') 0 0 / 6.5rem auto repeat-y",
        'linear-gradient(180deg, #2d2545 0%, #14121f 100%)',
      ].join(', '),
      '--rail-fg': '#fff4e6',
      '--rail-item-bg': 'rgb(20 18 31 / 0.78)',
      '--rail-active-bg': '#ffb000',
      '--rail-active-fg': '#14121f',
      '--rail-edge': '0.15rem 0 0.8rem rgb(0 0 0 / 0.45)',
    },
  },
  {
    id: 'summer',
    name: 'Summer',
    scheme: 'dark',
    season: { start: '06-01', end: '06-30' },
    // Deep ocean page, sand-white text, sun-yellow accent. The nav is open water with rolling
    // waves (public/themes/summer, from scripts/summer-waves.mjs) running down to a sand beach.
    tokens: {
      '--bg': '#0a2540',
      '--surface': '#0f3257',
      '--surface-2': '#174270',
      '--text': '#fdf6e3',
      '--text-muted': '#9fbcd6',
      '--accent': '#ffd166',
      '--danger': '#ff6b6b',
      '--success': '#5ee6a8',
      '--warn': '#ff8c69',
      '--font-display': "'Summer', var(--font-body)",
      // Layers, top first: the beach over the bottom of the nav, the waves, then the water.
      '--rail-bg': [
        'linear-gradient(180deg, transparent 0 82%, #f2cf7a 85%, #e2b45a 100%)',
        "url('/themes/summer/waves.svg') 0 0 / 6.5rem auto repeat",
        'linear-gradient(180deg, #2a86c9 0%, #0d4a86 80%)',
      ].join(', '),
      '--rail-fg': '#fdf6e3',
      '--rail-item-bg': 'rgb(10 37 64 / 0.78)',
      '--rail-active-bg': '#ffd166',
      '--rail-active-fg': '#0a2540',
      '--rail-edge': '0.15rem 0 0.8rem rgb(0 0 0 / 0.4)',
      // The sun-yellow + sits on the sand, so ring it in ocean blue.
      '--rail-add-ring': '0 0 0 0.25rem #0a2540',
    },
  },
  {
    id: 'july',
    name: '4th of July',
    scheme: 'dark',
    season: { start: '07-01', end: '07-31' },
    // Navy page, off-white text, flag-red accent. The nav is the flag on its side: a starred
    // navy canton (public/themes/july, from scripts/july-stars.mjs) over red and cream stripes.
    tokens: {
      '--bg': '#0d1b30',
      '--surface': '#14263f',
      '--surface-2': '#1d3557',
      '--text': '#f5f1e8',
      '--text-muted': '#a8b6c9',
      '--accent': '#e63946',
      '--danger': '#ff8a80',
      '--success': '#5ee6a8',
      '--warn': '#ffd166',
      '--font-display': "'July', var(--font-body)",
      // Layers, top first: the stars, the navy canton behind them, then the stripes.
      '--rail-bg': [
        "url('/themes/july/stars.svg') 0 0 / 6.5rem 18rem no-repeat",
        'linear-gradient(#1d3557, #1d3557) 0 0 / 100% 18rem no-repeat',
        'repeating-linear-gradient(180deg, #b22234 0 1.6rem, #f5f1e8 1.6rem 3.2rem)',
      ].join(', '),
      '--rail-fg': '#f5f1e8',
      '--rail-item-bg': 'rgb(13 27 48 / 0.88)',
      '--rail-active-bg': '#f5f1e8',
      '--rail-active-fg': '#b22234',
      '--rail-edge': '0.15rem 0 0.8rem rgb(0 0 0 / 0.45)',
      '--rail-add-ring': '0 0 0 0.25rem #f5f1e8',
    },
  },
  {
    id: 'school',
    name: 'School',
    scheme: 'dark',
    season: { start: '08-01', end: '08-31' },
    // Chalkboard page, chalk-white text, school-bus yellow accent. The nav is notebook paper,
    // drawn entirely with CSS: hole punches, a red margin line, blue rules, paper.
    tokens: {
      '--bg': '#1f2a25',
      '--surface': '#27352f',
      '--surface-2': '#33443c',
      '--text': '#f1f0e8',
      '--text-muted': '#a9b3ad',
      '--accent': '#ffb81c',
      '--danger': '#ff6b6b',
      '--success': '#8ce99a',
      '--warn': '#ff922b',
      '--font-display': "'School', var(--font-body)",
      '--rail-bg': [
        'radial-gradient(circle at 0.8rem 6rem, #1f2a25 0 0.35rem, transparent 0.4rem) 0 0 / 100% 12rem repeat-y',
        'linear-gradient(90deg, transparent 1.6rem, #e5484d 1.6rem 1.72rem, transparent 1.72rem)',
        'repeating-linear-gradient(180deg, transparent 0 1.45rem, #9cc3e6 1.45rem 1.55rem)',
        '#fbf8ef',
      ].join(', '),
      '--rail-fg': '#f1f0e8',
      '--rail-item-bg': 'rgb(31 42 37 / 0.92)',
      '--rail-active-bg': '#ffb81c',
      '--rail-active-fg': '#1f2a25',
      '--rail-edge': '0.15rem 0 0.8rem rgb(0 0 0 / 0.45)',
      // The yellow + sits on white paper, so ring it in chalkboard.
      '--rail-add-ring': '0 0 0 0.25rem #1f2a25',
    },
  },
  {
    id: 'fall',
    name: 'Fall',
    scheme: 'dark',
    season: { start: '09-01', end: '09-30' },
    // Twilight charcoal-olive page, parchment text, amber accent (kept clear of Halloween's
    // orange and Thanksgiving's rust). The nav has falling leaves (public/themes/fall, from
    // scripts/fall-leaves.mjs) over a dusk gradient.
    tokens: {
      '--bg': '#1a1a14',
      '--surface': '#25241b',
      '--surface-2': '#333126',
      '--text': '#f4ead5',
      '--text-muted': '#b8ad94',
      '--accent': '#e9a23b',
      '--danger': '#ff6b6b',
      '--success': '#a3d977',
      '--warn': '#ff7a45',
      '--font-display': "'Fall', var(--font-body)",
      '--rail-bg': [
        "url('/themes/fall/leaves.svg') 0 0 / 6.5rem auto repeat",
        'linear-gradient(180deg, #4a4330 0%, #1a1a14 100%)',
      ].join(', '),
      '--rail-fg': '#f4ead5',
      '--rail-item-bg': 'rgb(26 26 20 / 0.82)',
      '--rail-active-bg': '#e9a23b',
      '--rail-active-fg': '#1a1a14',
      '--rail-edge': '0.15rem 0 0.8rem rgb(0 0 0 / 0.45)',
    },
  },
];
